name: Retrieve AWS Secret and Variable

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - develop

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Firstly, insert your secrets in AWS Secret Manager
      # Then, you can retrieve the secrets based on your secret-id
      # If you have multiple secret key and value pairs like mine, you can parse
      # the entire json object and print the values you'd like to display/use

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id dev/ramesh_app/db --query SecretString --output json)

          # Parse specific keys from the secret object
          secret_value_phone=$(echo "$secret_object" | jq -r '. | fromjson | .ramesh_phone_model')
          secret_value_food=$(echo "$secret_object" | jq -r '. | fromjson | .ramesh_food')
          secret_value_loc=$(echo "$secret_object" | jq -r '. | fromjson | .Ramesh_location')

          echo "Secret value phone is: $secret_value_phone"
          echo "Secret value Food is: $secret_value_food"
          echo "Secret value Location is: $secret_value_loc"

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Firstly, insert your parameter in AWS Systems Manager > Parameter Store
      # Then, you can retrieve the parameters using aws ssm get-parameter command

      - name: Get parameter object
        run: |
          hobby_value=$(aws ssm get-parameter --name ramesh_hobby --query Parameter.Value --output text)
          echo "ramesh_hobby is: $hobby_value" 

          # hobby_value=$(aws ssm get-parameter --name ramesh_hobby --query Parameter.Value --output text)
          # echo "dev/ramesh_app/db is: $hobby_value" 